[RFR] Fix compatibility for Symfony 3.3 about autowire
coopTilleuls/CoopTilleulsMigrationBundle pull request #2
Opened 2017-06-01 08:35 UTC by vincentchalamon

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1
| License       | MIT

- Remove useless `alias` option on loader tags
- Remove useless `priority` option on loader tags
- Update documentation
- Update tests

2017-06-01 08:47 UTC, dunglas commented on .travis.yml
>            env: SYMFONY_VERSION=3.1.*
You may also add SF 3.2.

2017-06-01 08:58 UTC, vincentchalamon commented on .travis.yml
>            env: SYMFONY_VERSION=3.1.*
Better 3.3?

2017-06-06 07:21 UTC, vincentchalamon commented
Ping @dunglas @Simperfit @meyerbaptiste

2017-06-06 14:24 UTC, meyerbaptiste requested changes

2017-06-06 14:24 UTC, meyerbaptiste commented on .travis.yml
>  matrix:
I can't understand what is the goal of your matrix here because the `SYMFONY_VERSION` env var is never used.

2017-06-06 14:24 UTC, meyerbaptiste commented on .travis.yml
>          - deps=no
Same here, what is the goal of this env var?

2017-06-06 14:24 UTC, meyerbaptiste commented on .travis.yml
>  matrix:
You can remove PHP 5.3 and 5.4 from your matrix, there are useless.

2017-06-06 14:28 UTC, vincentchalamon commented on .travis.yml
>  matrix:
Fixed

2017-06-06 14:30 UTC, meyerbaptiste commented on .travis.yml
>  matrix:
And about my first question? 😛

2017-06-06 14:31 UTC, meyerbaptiste approved these changes

2017-06-06 17:47 UTC, Simperfit approved these changes

2017-06-06 18:05 UTC, meyerbaptiste requested changes

2017-06-06 18:05 UTC, meyerbaptiste commented on DependencyInjection/CoopTilleulsMigrationExtension.php
> +        $container->registerForAutoconfiguration(LoaderInterface::class)
You have to bump `symfony/dependency-injection` to `3.3` and adapt your Travis config!

2017-06-06 18:05 UTC, meyerbaptiste commented on DependencyInjection/Compiler/LoaderCompilerPass.php
> +            $loaders[] = new Reference($id);
If you bump `symfony/dependency-injection`to `3.3`, this is a good example to use a service locator! Same for your transformers! 😉

2017-06-06 18:08 UTC, meyerbaptiste commented on DependencyInjection/CoopTilleulsMigrationExtension.php
> +        $container->registerForAutoconfiguration(LoaderInterface::class)
Or test if the method exists...

2017-06-07 11:24 UTC, vincentchalamon commented on DependencyInjection/Compiler/LoaderCompilerPass.php
> +            $loaders[] = new Reference($id);
But if I bump it to 3.3, it will cause a BC break, isn't it?

2017-06-07 11:37 UTC, meyerbaptiste commented on DependencyInjection/Compiler/LoaderCompilerPass.php
> +            $loaders[] = new Reference($id);
If you bump it to 3.3 without changing your public API, no: http://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api

But, if you implement a service locator without backward compatibility, yes.

2017-06-07 14:15 UTC, vincentchalamon commented on DependencyInjection/Compiler/LoaderCompilerPass.php
> +            $loaders[] = new Reference($id);
But ServiceLocators are incompatible with this project (`LoaderRegistry` & `TransformerChain`), and would require a too big refacto to implement it. Maybe in another PR 😉

2017-06-09 14:19 UTC, vincentchalamon commented on DependencyInjection/Compiler/LoaderCompilerPass.php
> +            $loaders[] = new Reference($id);
Works for loaders, not for transformers. Talked about that with @Gregcop1, I'll create a Transformer annotation to connect an entity to its transformer, and use a service locator to get the final service and keep lazy services.

2017-06-14 12:44 UTC, Simperfit reviewed
It is not breaking some compatibility ? since you are removing the getName()

2017-06-14 12:46 UTC, vincentchalamon commented
@Simperfit I was talking about `symfony/symfony` dependency increased to >=3.3

2017-06-14 12:47 UTC, dunglas approved these changes

2017-06-14 13:42 UTC, meyerbaptiste requested changes

2017-06-14 13:42 UTC, meyerbaptiste commented on Command/MigrationLoadCommand.php
> +        /** @var LoaderInterface $loader */
Add a new empty line before this comment.

2017-06-14 13:42 UTC, meyerbaptiste commented on DependencyInjection/CoopTilleulsMigrationExtension.php
> +        if (method_exists($container, 'registerForAutoconfiguration')) {
This is useless with `symfony/dependency-injection: ^3.3` in your `composer.json` file.

2017-06-14 13:46 UTC, meyerbaptiste approved these changes

2017-06-14 13:53 UTC, merged